import React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  //calculator costuri emag
  const [pretVanzare, setPretVanzare] = React.useState(0);
  const [costTransport, setCostTransport] = React.useState(0);

  return (
    <div className={styles.container}>
      <Head>
        <title>Calculator costuri eMag</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Calculator costuri/profit eMag
        </h1>

        <p className={styles.description}>
          <div className='flex flex-col'>
            <div>
              <label htmlFor="price">Pret vanazare produs:</label>
            </div>
            <div className='p-2'>
              <input onChange={e => setPretVanzare(e.target.value)} type="number" placeholder="Pret vanzare produs" />
            </div>
            <div className='p-2'>
              <input onChange={e => setCostTransport(e.target.value)} type="number" placeholder="Cost transport" />
            </div>
            <p>Costuri: {pretVanzare * 0.25} RON</p>
            <p>Profit: {pretVanzare * 0.75} RON</p>
            {/* <p>{(function () {
              console.log('IIFE');
            })()}</p> */}
          </div>
        </p>


      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
